version: "2.0"
 
services:
  gbd:
    hostname: gbd
    build: ./GBD
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "4040:3306"

  web:
    depends_on: 
      - gbd
    hostname: web
    build: ./WEB
    restart: always
    ports:
      - "8080:80"
