version: "2.0"
 
services:
  gbd:
    hostname: gbd
    build: ./GBD
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "4040:3306"

  web:
    depends_on: 
      - gbd
    hostname: web
    build: ./WEB
    restart: always
    ports:
      - "8080:80"
    links: 
      - gbd
